name: nodejs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
     - name: Setup Node
       uses: actions/setup-node@v1
       with:
          node-version: '18.x'
     - name: Debug
       run: "dir .."
     - name: Yarn Dependancy Installation
       run: "yarn install"
     - name: Yarn Build
       run: "yarn build"
     - name: Post Build
       run: "yarn build:post"
     - name: Rename Output
       run: "mv ./dist/index.exe ./dist/pdanetshenanigans.exe"
     - name: Upload exe
       uses: actions/upload-artifact@v3.1.2
       with:
        name: "build"
        path: "./dist/pdanetshenanigans.exe"
